<?php
if ( isset( $this->include ) ) :
	foreach ( $this->include as $include ) :
?>
<script type="text/javascript" src="<?php echo $include; ?>"></script><?php
	endforeach;
endif;
if ( isset( $this->plain ) || isset( $this->ready ) ) : ?>
<script type="text/javascript">
//<![CDATA[
<?php echo $this->plain->indent( 1 );
if ( isset( $this->ready ) ) : ?>
	jQuery( function ( $ ) {
<?php echo $this->ready->indent( 2 ); ?>
	} );
<?php endif; ?>
//]]>
</script><?php
endif; ?>