<?php $this->js( 'ligne1;' );?>
<table cellpadding="3" border="0" cellspacing="1" bgcolor="#CCCCCC">
	<tr>
		<td bgcolor="#F0F0F0">Id</td>
		<td bgcolor="#F0F0F0">Name</td>
		<td bgcolor="#F0F0F0">Email</td>
		<td bgcolor="#F0F0F0">Banned</td>
	</tr>
<?php foreach( $this->users as $user ): ?>
	<tr>
		<td bgcolor="#FFFFFF" align="center"><?=$user['id'];?></td>
		<td bgcolor="#FFFFFF"><?=$user['name'];?></td>
		<td bgcolor="#FFFFFF"><a href="mailto:<?=$user['email'];?>"><?=$user['email'];?></a></td>
		<td bgcolor="#FFFFFF" align="center"><?=($user['banned'] ? 'X' : '&nbsp;');?></td>
	</tr>
<?php endforeach; ?>
<?php $this->js( 'ligne2();' );?>
</table>