<html>
	<head>
		<title><?= $title; ?></title>
<?php 
	echo $this
			->js( 'var line3 = 
"line4";' )
			//->append( 'jquery', '1.4.2' )
			->append( 'console && console.log( test );', 'ready' )
			->indent( 2 ),
		$this
			->css( 'http://code.jquery.com/mobile/1.1.0/jquery.mobile-1.1.0.min.css', 'phone' )
			->indent( 2 ),
		$this
			->css( 'body{ color: #444; }' )
			->prepend( 'warning', 'table' )
			->prepend( 'textShadow', 'h1' )
			->indent( 2 ),
			'<!--[if lte IE 7]>' ,
			$this->css( 'ie.css', 'iesucks' ), 
			'<![endif]-->'
	;
?>
	</head>
	<body>
		<h1><?= $this->title; ?></h1>
<?php 
	$this->js( 'var test = ', 'inline' );
	echo $this->content,
		 $this->js( '"test";', 'inline' )->indent( 2 ),
		 $this->tpl()->append( 'no template => debug' )
	;
?>
	</body>
</html>